eAlgoritmo "areaQuadrado"
// Disciplina   :Programação de Algoritimos
// Professor   : Cintia Pino
// Descrição   : Calculo da area do quadrado
// Autor(a)    : Rafael Lima de Oliveira
// Data atual  : 12/03/2021
Var
//lado variavel de entrada
// area variavel de processamento e saida
lado,area: real


Inicio

//entrada
escreval("Digite o lado do quadrado: ")
leia(lado)


//processamento
area <-lado*lado


//saida
escreval("area do quadrado e:",area,"m2")

Fimalgoritmo